%modifierad 990318 Fredrik Altenstedt
% ändrat Trixat med iterationsantal
setoffilp
for slaskvar =1:iterantal
  if metod==1 & fkn < 9 
    steepest
  end

  if metod==1 & fkn > 8 
    steepestmy
  end

  if metod==2 & fkn < 9
    newtonmod
  end

  if metod==2 & fkn > 8
    newtonmodmy
  end

  if metod==3 & fkn < 9
    marquardt
  end

  if metod==3 & fkn > 8
    marquardtmy
  end

  if metod==4 & fkn < 9
    newt
  end

  if metod==4 & fkn > 8
    newtmy
  end

  if ~(i < maxiter & slut == 0 & ww1 == 1 & stlgd == 1)
     break;
  else
     i = i + 1; 
  end
end
setonilp
if i < maxiter & slut == 0 & ww1 == 1 & stlgd == 1
  if utskrift=='På'
    if forsta == 1
      men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[300 170 120 20], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string','Function value' , ...
	'Tag','StaticText1');
      men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[300 155 120 20], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string','Iteration point' , ...
	'Tag','StaticText1');
      men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[300 125 120 20], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string','Iteration' , ...
	'Tag','StaticText1');
      forsta = 0;
    end
    if fkn > 8
      funkvarde = num2str(feval(funktion,x,my));
    else
      funkvarde = num2str(feval(funktion,x));
    end
    men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[440 170 80 20], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string',funkvarde , ...
	'Tag','StaticText1');
    men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[440 155 80 20], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string',x(1), ...
	'Tag','StaticText1');
    men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[440 140 80 20], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string',x(2), ...
	'Tag','StaticText1');
    men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[440 125 80 20], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string',i , ...
	'Tag','StaticText1');
  end
  if ~exist('loopkorning')
    startfil;
  end
else
  if ww1 == 0
    if fkn > 8
      whitecomnotmy
      whitelosilp
    else
      whiteallilp
    end
    men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[1 0 0], ...
	'Units','points', ...
	'Position',[30 40 250 20], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string','Can not calucate next iteration point', ...
	'Tag','StaticText1');
    ww1 = 1;
    return
  end
  if stlgd == 0
    if fkn > 8
      whitecomnotmy
      whitelosilp
    else
      whiteallilp
    end
    men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[1 0 0], ...
	'Units','points', ...
	'Position',[30 40 250 20], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string','The steplength equals zero', ...
	'Tag','StaticText1');
    stlgd = 1;
    return
  end
  men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[340 50 140 70], ...
	'Style','text', ...
	'String','', ...
	'Tag','StaticText1');
  if i >= maxiter
    men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[1 0 0], ...
	'Units','points', ...
	'Position',[10 40 300 20], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string','Max No. of iterations reached', ...
	'Tag','StaticText1');
  else
    if fkn > 8
      whitecomnotmy
    else
      whitecomilp    
    end
  end 
    men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[300 188 200 20], ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string','Solution data', ...
	'Tag','StaticText1');
    if fkn > 8
      funkvarde = num2str(feval(funktion,x,my));
    else
      funkvarde = num2str(feval(funktion,x));
    end
    men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[300 170 120 20], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string','Function value' , ...
	'Tag','StaticText1');
    men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[440 170 80 20], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string',funkvarde , ...
	'Tag','StaticText1');

    men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[300 155 120 20], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string','Solution point' , ...
	'Tag','StaticText1');
    men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[440 155 80 20], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string',x(1), ...
	'Tag','StaticText1');

    men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[440 140 80 20], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string',x(2), ...
	'Tag','StaticText1');

    men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[300 125 120 20], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string','No. of iterations' , ...
	'Tag','StaticText1');
    men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[440 125 80 20], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string',i, ...
	'Tag','StaticText1');
  yyy = 1;
end


