men1= uicontrol('Parent',men, ...
	'ForegroundColor',[0 0 0], ...
	'BackgroundColor',[1 1 1], ...
       	'Units','points', ...
	'fontsize',12, ... 
	'Position',[85 70 150 20], ...
	'Horizontalalignment','right', ...
	'Style','text', ...
	'string','Give my [0.005 1000]:',...
	'Tag','StaticText1');
men1= uicontrol('Parent',men, ...
	'Units','points', ...
	'BackgroundColor',[0.9 0.7 0.7], ...
	'Horizontalalignment','left', ...
	'fontsize',12, ... 
	'Position',[235 75 60 20], ...
	'Callback','nyttmyfil', ...
	'Style','edit', ...
	'Tag','EditText1');


