mypoint = get(gcbo,'String'); 
if mypoint(1) ~= '['
  mypoint1 = ['[' mypoint];
    if mypoint1(length(mypoint)) ~= ']'
      mypoint = [ mypoint1 ']'];
    end
end
my = str2num(mypoint);

nyttmy = 1;
if size(my,2) ~= 1
  men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[1 0 0], ...
	'Units','points', ...
	'Position',[30 40 250 20], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string','Error in input data', ...
	'Tag','StaticText1');
  return
end
if my < 0.005 | my > 1000
  men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[1 0 0], ...
	'Units','points', ...
	'Position',[30 40 250 20], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string','My must belong to the interval [0.005 1000]', ...
	'Tag','StaticText1');
  return
else
men1= uicontrol('Parent',men, ...
	'ForegroundColor',[0 0 0], ...
	'BackgroundColor',[1 1 1], ...
       	'Units','points', ...
	'fontsize',12, ... 
	'Position',[92 70 210 25], ...
	'Horizontalalignment','right', ...
	'Style','text', ...
	'string','',...
	'Tag','StaticText1');
setoffilp;
rita;
mymeny;
setonilp;
end
yyy = 0;
