spoint = get(gcbo,'String'); 
if spoint(1) ~= '['
  spoint1 = ['[' spoint];
    if spoint1(length(spoint)) ~= ']'
      spoint = [ spoint1 ']'];
    end
end
startpoint = str2num(spoint);
if size(startpoint,2) ~= 2
  men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[1 0 0], ...
	'Units','points', ...
	'Position',[30 40 250 20], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string','Give x and y coordinates', ...
	'Tag','StaticText1');
  return
else
  if fkn == 9
    whitecomnotmy
    whitelosilp
  else
    whiteallilp
  end
  startpkt = spoint;
  men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Units','points', ...
	'Position',[10 166 140 20], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string',startpkt, ...
	'Tag','StaticText1');
end
setoffilp;
rita
setonilp;
yyy = 0;
i = 0;
