if utskrift == 'På'
  utskrift = 'Av';
else
  utskrift = 'På';
end
men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Units','points', ...
	'Position',[155 122 140 20], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string',utskrift, ...
	'Tag','StaticText1');
