men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Units','points', ...
	'Position',[10 40 300 35], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string','', ...
	'Tag','StaticText1');

men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Units','points', ...
	'Position',[92 75 220 21], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string','', ...
	'Tag','StaticText1');

%HENRY
men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Units','points', ...
	'Position',[438 0 80 8], ...	
	'Style','text', ...
 	'Fontsize',8, ...
	'string','', ...
	'Tag','StaticText1');


