men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
        'Fontsize',12, ...
	'Units','points', ...
	'Position',[4 80 700 20], ...
	'Style','text', ...
	'Tag','StaticText3');
men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
        'Fontsize',12, ...
	'Units','points', ...
	'Position',[4 66 700 20], ...
	'Style','text', ...
	'Tag','StaticText3');
men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
        'Fontsize',12, ...
	'Units','points', ...
	'Position',[4 52 700 20], ...
	'Style','text', ...
	'Tag','StaticText3');
men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
        'Fontsize',12, ...
	'Units','points', ...
	'Position',[4 38 700 20], ...
	'Style','text', ...
	'Tag','StaticText3');
men1= uicontrol('Parent',men, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[275 3 148 25], ...
	'Style','text', ...
	'Tag','Statictext3');
men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Units','points', ...
	'Position',[630 0 80 8], ...
	'Style','text', ...
	'Tag','StaticText3');

