%  men1= uicontrol('Parent',men, ...
%	'BackgroundColor',[1 1 1], ...
%       	'Units','points', ...
%	'fontsize',12, ... 
%	'Position',[10 70 235 20], ...
%	'Style','text', ...
%	'string',' ',...
%	'Tag','StaticText1');
%  men1= uicontrol('Parent',men, ...
%	'Units','points', ...
%	'BackgroundColor',[1 1 1], ...
%	'fontsize',12, ... 
%	'Position',[235 75 60 20], ...
%	'Style','text', ...
%	'string',' ',...
%	'Tag','StaticText1');
men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Units','points', ...
	'Position',[10 40 300 58], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string','', ...
	'Tag','StaticText1');

%HENRY
men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Units','points', ...
	'Position',[438 0 80 8], ...	
	'Style','text', ...
 	'Fontsize',8, ...
	'string','', ...
	'Tag','StaticText1');

