% Lösningsdata
men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Position',[300 125 220 85], ...
	'Horizontalalignment','left', ...
	'Style','text', ...
 	'Fontsize',12, ...
	'string',' ' , ...
	'Tag','StaticText1');
men1 = uicontrol('Parent',men, ...
	'Units','points', ...
	'BackgroundColor',[1 1 1], ...
	'Position',[340 70 150 70], ...
	'Style','text', ...
	'String','', ...
	'Tag','StaticText1');
%HENRY
men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Units','points', ...
	'Position',[438 0 80 8], ...	
	'Style','text', ...
 	'Fontsize',8, ...
	'string','', ...
	'Tag','StaticText1');

