%path(path,'/mailocal/lab/opt/matlab/ILP')
%path(path,'/mailocal/lab/opt/matlab/ILPFUNKTIONER')
%path(path,'/mailocal/lab/opt/matlab/ILPMETODER')

path(path,'ILP')
path(path,'ILPFUNKTIONER')
path(path,'ILPMETODER')

warning off
if exist('men') 
  disp('Ett menyfönster är redan öppnat, Avsluta innan Ni öppnar ett nytt')
  return
end
echo off
close all
clc
colordef white
svar = 0;
i = 0;
ww1 = 1;
stlgd = 1;
yyy = 0;
nyttmy = 0;
if ~exist('borjan')
  borjan = 0;
end
if borjan == 0
  funktyp = 'Funktion 1 (kvadratisk)';
  fkn = 1;
  metodtyp='Brantaste lutning';
  metod = 1;
  startpkt ='[0 0]';
  startpoint = [0 0];
  avbrottstyp = 'Gradientlängd';
  avb=0.0001;
  normavbrott=0.01;
  avstandavbrott=0;
  antaliter='200';
  maxiter = 201;
  utskrift='På';
  borjan = 1;
end
nytt = 1;                            
men = figure('Color', [1 1 1], ...
 	'Position',[256 480 650 270], ...
	'Numbertitle','off', ...
        'Name','Meny', ...
	'Resize','off', ...
        'CloseRequestFcn','avslutailpfil', ...  
 	'Menubar', 'none', ...
	'Tag','Fig1');
% 	'Position',[256 503 570 240], ...

menst = uicontrol('Parent',men, ...
	'Units','points', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Position',[10 188 140 20], ...
	'String','Starting point', ...
	'callback','startpktfil', ...
	'Tag','Pushbutton1');
	
men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Units','points', ...
	'Position',[10 166 140 20], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string',startpkt, ...
	'Tag','StaticText1');

menmax = uicontrol('Parent',men, ...
	'Units','points', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Position',[155 188 140 20], ...
	'String','Max No. of Iterations', ...
 	'callback', 'itermeny', ...
	'Tag','Pushbutton1');

men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Units','points', ...
	'Position',[155 166 140 20], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string',antaliter, ...
	'Tag','StaticText1');

menavb = uicontrol('Parent',men, ...
	'Units','points', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Max',2, ...
	'Min',1, ...
	'Position',[10 144 140 20], ...
	'String',['Term. on: Gradient length   ';'Term. on: Iteration distance'], ...
 	'Callback','avbrottfil', ...
	'Style','popupmenu', ...
	'Tag','PopupMenu1', ...
	'Value',1);
men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Units','points', ...
	'Position',[10 122 140 20], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string',avb, ...
	'Tag','StaticText1');

menut = uicontrol('Parent',men, ...
	'Units','points', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Position',[155 144 140 20], ...
        'callback','utskriftfil', ...
	'String','Print iteration data', ...
	'Tag','Pushbutton1');
men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Units','points', ...
	'Position',[155 122 140 20], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string',utskrift, ...
	'Tag','StaticText1');

menfkn = uicontrol('Parent',men, ...
	'Units','points', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Max',4, ...
	'Min',1, ...
	'Position',[10 100 140 20], ...
        'callback','fknfil', ...
	'String',['Function 1 ';'Function 2 ';'Function 3 ';'Function 4 ';'Function 5 ';'Function 6 ';'Function 7 ';'Function 8 ';'SUMT func 1';], ...
	'Style','popupmenu', ...
	'Tag','PopupMenu1', ...
	'Value',1);

menmet = uicontrol('Parent',men, ...
	'Units','points', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Max',3, ...
	'Min',1, ...
	'Position',[155 100 140 20], ...
	'callback','metodfil' , ...
	'String',[' Steepest descent   ';' Newton, modified   ';' Newton (Marquardt) ';'  Newton (unit step)'], ...
	'Style','popupmenu', ...
	'Tag','PopupMenu1', ...
	'Value',1);

menstarta = uicontrol('Parent',men, ...
	'Units','points', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Position',[80 5 140 35], ...
	'String','Start', ...
        'callback','starta', ...
	'Tag','Pushbutton1');
menavs = uicontrol('Parent',men, ...
	'Units','points', ...
	'BackgroundColor',[0.701961 0.701961 0.701961], ...
	'Position',[340 10 100 25], ...
	'String','Quit', ...
 	'callback','avslutailp', ...
	'Tag','Pushbutton1');

setoffilp
rita
setonilp

men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Units','points', ...
	'Position',[30 40 250 20], ...	
	'Style','text', ...
 	'Fontsize',12, ...
	'string','Change the settings or choose Start', ...
	'Tag','StaticText1');
men1= uicontrol('Parent',men, ...
	'Backgroundcolor',[1 1 1], ...
	'Foreground',[0 0 0], ...
	'Units','points', ...
	'Position',[438 0 80 8], ...	
	'Style','text', ...
 	'Fontsize',8, ...
	'string','(c) HENRY, Mai Opt', ...
	'Tag','StaticText1');


